Login form and progress bar edits
SheCodesAus/fully_committed_group_2023_frontend pull request #52
Opened 2023-04-05 12:23 UTC by samjsh

Please note: No edits made to PageContent that affect functionality. Upon saving the page my IDE made some spacing changes and changed ' to "" and I just left it.

{{CHANGED FUNCTIONALITY}}
Edited the ProgressBar code to make it custom for this project and implemented it into the ProgramDetailPage & the SessionDetailPage. Have also added 'PageContent' to SessionDetailPage to make it more consistent.

2023-04-05 14:07 UTC, Simplicity305 requested changes
Hey, could you please remove the image from the login form?

Also, did you make any changes at that level? The PR and branch name indicates login form but cant see any changes for this?

2023-04-05 20:52 UTC, builtbyproxy commented on src/Components/ProgressBar/ProgressBar.jsx
> +  const containerStyles = {
[This is a good read](https://www.syncfusion.com/blogs/post/10-javascript-naming-conventions-every-developer-should-know.aspx#:~:text=Naming%20Convention%20for%20Constants) for the naming convention of these `const` variables 👍

2023-04-05 20:55 UTC, builtbyproxy commented on src/Pages/ProgramDetailPage.jsx
> +            }
I'd try and write the calculation itself a little more readable on one line like so: 
```suggestion
            completed={
              programData.mentors_required > 0
                ? (programData.mentors_assigned / programData.mentors_required) * 100
                : 0
            }
```

The indentation of `?` and `:` on their own lines is really nice for readability! Great work 🎉

2023-04-06 01:12 UTC, samjsh commented
> Hey, could you please remove the image/logo from the login form?
> 
> Also, did you make any changes at that level? The PR and branch name indicates login form but cant see any changes for this?

Hey, yep initially I intended to make edits to the LoginForm and the ProgressBar in the same work but ended up just working on the ProgressBar. Do we still need to the LoginForm edits before merging this as I plan to attack this in another piece of work. I just want to get the progress bar in before any conflicts.

2023-04-06 01:14 UTC, merged